services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/taxi_app
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/src
    ports:
      - "80:3000"
    depends_on:
      - backend
    env_file:
      - .env

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taxi_app
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db_data:
